export default [
    {id: 1, name: '大王', head: 'images/dawang.jpeg'},
    {id: 2, name: 'Un1C', head: 'images/header_unic.jpeg'},
    {id: 3, name: 'Jacky Wu', head: 'images/jackyWu.jpeg'},
    {id: 4, name: 'God Loves You', head: 'images/godlovesyou.jpeg'},
    {id: 5, name: '杨洋', head: 'images/yangyang.jpeg'},
    {id: 6, name: 'Juve1997大王叫我来巡山', head: 'images/1997xiaolaodi.jpeg'},
    {id: 7, name: '2018新米屌启航 Fozza Merda', head: 'images/xinmidiaoqihang.jpeg'},
    {id: 8, name: 'Alan35', head: 'images/alan35.jpeg'},
    {id: 9, name: 'ice', head: 'images/ice.jpg'},
    {id: 10, name: 'Kevin Tracy', head: 'images/kevinTracy.jpeg'},
    {id: 11, name: '丁涛', head: 'images/dingtao.jpeg'},
    {id: 12, name: 'Uno Generale', head: 'images/unogenerale.jpeg'},
    {id: 13, name: '松哥', head: 'images/songge.jpeg'},
    {id: 14, name: '小绿', head: 'images/xiaolv.jpeg'},
    {id: 15, name: 'wyf', head: 'images/wyf.jpeg'},
    {id: 16, name: 'ye', head: 'images/ye.jpeg'},
    {id: 17, name: '江鹏', head: 'images/jiangpeng.jpeg'},
    {id: 18, name: 'Del', head: 'images/del.jpeg'},
    {id: 19, name: 'pope', head: 'images/pope.jpeg'},
    {id: 20, name: '大灰狼', head: 'images/dahuilang.jpeg'},
    {id: 21, name: 'Jelly', head: 'images/jelly.jpeg'},
    {id: 22, name: 'Jichao', head: 'images/jichao.jpeg'},
    {id: 23, name: '骆驼祥子', head: 'images/luotuoxiangzi.jpeg'},
    {id: 24, name: '牛肉', head: 'images/niurou.jpeg'},
    {id: 25, name: '咖啡因boy', head: 'images/kafeiyin.jpeg'},
    {id: 26, name: '郭子豪', head: 'images/guozihao.jpeg'}
];
